### ISSUE TITLE
Estudio del despliegue de la aplicación similar a Heroku

### ISSUE THREAD

**Issue by clopezno** [ada1012/eLearningQA#18]

**Comment by ada1012** [comment]
Utilizando mvn heroku:deploy se buildea la imagen correctamente si embargo con la integración a través de github al no estar el archivo Procfile en el directorio raíz se buildea de forma incorrecta.

Por otro lado se lanza una java.lang.NullPointerException: null en el archivo login.jsp

**Comment by clopezno** [comment]
Consulta la documentación que dejó Roberto en esta  issue  "[Add continuous integration in repository and continuous deployment on Heroku server](https://github.com/RobertoArastiBlanco/eLearningQA/issues/12)"
