### ISSUE TITLE
Actualizar readme - manual de usuario - about 

### ISSUE THREAD

**Issue by clopezno** [ada1012/eLearningQA#23]

**Comment by clopezno** [comment]
Falta actualizar el contenido del Readme de Github.
En la documentación cuando se debe añadir tu autoría conservando la de Roberto. Es decir, no hay que eliminar a Roberto como autor del proyecto en toda la documentación.

**Comment by ada1012** [comment]
Modificaré el manual y el about de la aplicación volviendo a comentar a Roberto como autor de la primera versión. Respecto al readme utilizaré la issue #21 la cuál se centra en revisar dicho readme

**Comment by clopezno** [comment]
De acuerdo con tu propuesta.
